<b>Заявка</b>
 <?php if ($this->error): ?>
        <p class="error">
            Пожалуйста введите правильные данные.
        </p>
        <?php endif ?>
<?php 
$form = $this->form;
$form->prepare();
 
echo $this->form()->openTag($form);
?>
         <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('zayav')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('zayav'));
            echo $this->formElementErrors($form->get('zayav'));
        ?></dd>
        <dt><?php echo $this->formLabel($form->get('email')); ?>
        </dt>
        <dd><?php
            echo $this->formElement($form->get('email'));
           // echo $this->formElementErrors($form->get('email'));
        ?></dd>
        <dt><?php echo $this->formLabel($form->get('telephone'));
        ?></dt>
        <dd><?php
            echo $this->formElement($form->get('telephone'));
            echo $this->formElementErrors($form->get('telephone'));
        ?></dd>
       <dt><?php echo $this->formLabel($form->get('userdata'));
        ?></dt>
        <dd><?php
            echo $this->formElement($form->get('userdata'));
            echo $this->formElementErrors($form->get('userdata'));
        ?></dd>
      
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
        ?></dd>
        </dl>
          <?php echo $this->form()->closeTag() ?>
